
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cart-example-valinux-co-jp-v1alpha1-cart
  failurePolicy: Fail
  name: vcart.kb.io
  rules:
  - apiGroups:
    - cart.example.valinux.co.jp
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - carts
  sideEffects: None
