# permissions for end users to view carts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cart-viewer-role
rules:
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - carts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - carts/status
  verbs:
  - get
