
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - carts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - carts/finalizers
  verbs:
  - update
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - carts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - pricelists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - pricelists/finalizers
  verbs:
  - update
- apiGroups:
  - cart.example.valinux.co.jp
  resources:
  - pricelists/status
  verbs:
  - get
  - patch
  - update
